### ISSUE TITLE
Consuming SAP HANA Cloud from the Kyma environment

### ISSUE THREAD

**Issue by ptesny** [SAP-samples/btp-kyma-multitenant-extension#41]
Hello, following the [announcement](https://blogs.sap.com/2022/12/15/consuming-sap-hana-cloud-from-the-kyma-environment) of the availability of SAP HANA Cloud database instances mapping with SAP BTP.Kyma runtime clusters are you planning to remove the CF environment tie-in from this sample? kind regards;

**Comment by AlexRieder** [comment]
Hi Piotr, 

yes we are planning to remove the CF dependency and consume SAP HANA Cloud directly from the kyma environment. We do not have a concrete timeline for that but most likely we are aiming for a release End of Q1. 

Best regards
Alex

**Comment by AlexRieder** [comment]
Hi Piotr, 

with todays updates the dependency to the CF Environment is gone. The SAP HANA Cloud database can be consumed directly now. 
Pull request of the change: #42 

Best regards
Alex
